version: '3'
services:
  frontend:
    build: frontend
    ports:
      - 80:80
    volumes:
      - ./frontend/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
      - run:/run
      - ./backend/static:/static
      - ./backend/media:/media

  backend:
    build: backend
    command: ./entrypoint.sh
    volumes:
      - run:/run
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    depends_on:
      - database
  
  database:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_USER=testuser
      - POSTGRES_DB=default
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  run:
  dbdata: